### ISSUE TITLE
New template

### ISSUE THREAD

**Issue by cpshaw99** [theblacksea/issues#6]
Use Victor A's code, slightly modified, to create a new template for theblacksea.eu. 

https://theblacksea.eu/malta-files/article/en/erdogans-son-in-law-off-shore-tax-scheme

There are some suggested additions to this:

1. Slightly bigger font
2. White background 
3. That the Black Sea "menu bar" at the top sticks when you scroll down.  
4. The size of the photos should be flexible.
5. Option to upload videos, animation and graphics with varying size 
6. Facebook comments section
7. Font compatible with Turkish, Romanian and Russian. (Can be customised, bold, italics, etc) 
8. 

Black Sea border at top
Main picture (which is also the main picture for thumbnails, sharing on FB, Twitter)
Headline
Standfirst
Names (which need to be linked to names on site, about us page)
Date
Text (to be as flexible as possible - IE - we can change size, use bold and italics, add lines etc)
Subheadlines
Photos or multimedia
Photo captions (which can be used or left empty)
Icons on right

    At the end - ‘Follow us’, plus icons for following The Black Sea site itself on Twitter/Facebook https://twitter.com/TheBlackSeaEU and https://www.facebook.com/TheBlackSeaEU
    Links to other similar articles ‘Explore Further’ and then three thumbnails with the titles of stories, like this: https://theblacksea.eu/malta-files/
    This can be followed by the comments

**Comment by MichaelEIC** [comment]
The idea is to make an automated site structure that non-technical journalists can use on the platform of this article: 

https://theblacksea.eu/malta-files/article/en/erdogans-son-in-law-off-shore-tax-scheme


Issues to take into account


- The size of the photos needs to be flexible.
- There needs to be the option to upload videos, animation and graphics of varying sizes [which you say is doable]
- Keep the comments
- Ensure it is visible on Mobiles
- Ensure it can use languages which have different letters (mainly Turkish and Romanian, but there might come a time when we use Russian).
- Ensure the page does not open in a new window, so that the ‘back’ buttons can be used
- Ensure the page is visible in the search tool on The Black Sea site, which these pages are not at present
- Can we have the ability to edit URLs?
- Can we freeze the menu bar banner showing THE BLACK SEA DIVING DEEP INTO STORIES BLOGS STORIES ABOUT so it is always visible as you scroll - the new page doesn’t do that.
It should be like this: https://theblacksea.eu/malta-files/article/en/erdogan-family-secret-offshore-ship-deal 


Basic Structure to Maintain


Black Sea border at top
Main picture (which is also the main picture for thumbnails, sharing on FB, Twitter)
Headline
Standfirst
Names (which need to be linked to names on site, about us page)
Date
Text (to be as flexible as possible - IE - we can change size, use bold and italics, add lines etc)
Subheadlines
Photos or multimedia
Photo captions (which can be used or left empty)
Icons on right


Additions to make


Tags (they do not need to be visible)
- At the end - ‘Follow us’, plus icons for following The Black Sea site itself on Twitter/Facebook https://twitter.com/TheBlackSeaEU and https://www.facebook.com/TheBlackSeaEU
- Links to other similar articles ‘Explore Further’ and then three thumbnails with the titles of stories, like this: https://theblacksea.eu/malta-files/ 
- This can be followed by the comments

**Comment by mgax** [comment]
We can close this issue. @nightsh help? :)
